package swe;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Assignment <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public interface Assignment extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#has_report
     */
     
    /**
     * Gets all property values for the has_report property.<p>
     * 
     * @returns a collection of values for the has_report property.
     */
    Collection<? extends Progress_Report> getHas_report();

    /**
     * Checks if the class has a has_report property value.<p>
     * 
     * @return true if there is a has_report property value.
     */
    boolean hasHas_report();

    /**
     * Adds a has_report property value.<p>
     * 
     * @param newHas_report the has_report property value to be added
     */
    void addHas_report(Progress_Report newHas_report);

    /**
     * Removes a has_report property value.<p>
     * 
     * @param oldHas_report the has_report property value to be removed.
     */
    void removeHas_report(Progress_Report oldHas_report);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assignment_id
     */
     
    /**
     * Gets all property values for the assignment_id property.<p>
     * 
     * @returns a collection of values for the assignment_id property.
     */
    Collection<? extends Integer> getAssignment_id();

    /**
     * Checks if the class has a assignment_id property value.<p>
     * 
     * @return true if there is a assignment_id property value.
     */
    boolean hasAssignment_id();

    /**
     * Adds a assignment_id property value.<p>
     * 
     * @param newAssignment_id the assignment_id property value to be added
     */
    void addAssignment_id(Integer newAssignment_id);

    /**
     * Removes a assignment_id property value.<p>
     * 
     * @param oldAssignment_id the assignment_id property value to be removed.
     */
    void removeAssignment_id(Integer oldAssignment_id);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assignment_title
     */
     
    /**
     * Gets all property values for the assignment_title property.<p>
     * 
     * @returns a collection of values for the assignment_title property.
     */
    Collection<? extends String> getAssignment_title();

    /**
     * Checks if the class has a assignment_title property value.<p>
     * 
     * @return true if there is a assignment_title property value.
     */
    boolean hasAssignment_title();

    /**
     * Adds a assignment_title property value.<p>
     * 
     * @param newAssignment_title the assignment_title property value to be added
     */
    void addAssignment_title(String newAssignment_title);

    /**
     * Removes a assignment_title property value.<p>
     * 
     * @param oldAssignment_title the assignment_title property value to be removed.
     */
    void removeAssignment_title(String oldAssignment_title);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#ps_link
     */
     
    /**
     * Gets all property values for the ps_link property.<p>
     * 
     * @returns a collection of values for the ps_link property.
     */
    Collection<? extends URI> getPs_link();

    /**
     * Checks if the class has a ps_link property value.<p>
     * 
     * @return true if there is a ps_link property value.
     */
    boolean hasPs_link();

    /**
     * Adds a ps_link property value.<p>
     * 
     * @param newPs_link the ps_link property value to be added
     */
    void addPs_link(URI newPs_link);

    /**
     * Removes a ps_link property value.<p>
     * 
     * @param oldPs_link the ps_link property value to be removed.
     */
    void removePs_link(URI oldPs_link);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
