package swe;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Course <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public interface Course extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#has_assignment
     */
     
    /**
     * Gets all property values for the has_assignment property.<p>
     * 
     * @returns a collection of values for the has_assignment property.
     */
    Collection<? extends Assignment> getHas_assignment();

    /**
     * Checks if the class has a has_assignment property value.<p>
     * 
     * @return true if there is a has_assignment property value.
     */
    boolean hasHas_assignment();

    /**
     * Adds a has_assignment property value.<p>
     * 
     * @param newHas_assignment the has_assignment property value to be added
     */
    void addHas_assignment(Assignment newHas_assignment);

    /**
     * Removes a has_assignment property value.<p>
     * 
     * @param oldHas_assignment the has_assignment property value to be removed.
     */
    void removeHas_assignment(Assignment oldHas_assignment);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#offered_by
     */
     
    /**
     * Gets all property values for the offered_by property.<p>
     * 
     * @returns a collection of values for the offered_by property.
     */
    Collection<? extends Department> getOffered_by();

    /**
     * Checks if the class has a offered_by property value.<p>
     * 
     * @return true if there is a offered_by property value.
     */
    boolean hasOffered_by();

    /**
     * Adds a offered_by property value.<p>
     * 
     * @param newOffered_by the offered_by property value to be added
     */
    void addOffered_by(Department newOffered_by);

    /**
     * Removes a offered_by property value.<p>
     * 
     * @param oldOffered_by the offered_by property value to be removed.
     */
    void removeOffered_by(Department oldOffered_by);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#course_joining_code
     */
     
    /**
     * Gets all property values for the course_joining_code property.<p>
     * 
     * @returns a collection of values for the course_joining_code property.
     */
    Collection<? extends String> getCourse_joining_code();

    /**
     * Checks if the class has a course_joining_code property value.<p>
     * 
     * @return true if there is a course_joining_code property value.
     */
    boolean hasCourse_joining_code();

    /**
     * Adds a course_joining_code property value.<p>
     * 
     * @param newCourse_joining_code the course_joining_code property value to be added
     */
    void addCourse_joining_code(String newCourse_joining_code);

    /**
     * Removes a course_joining_code property value.<p>
     * 
     * @param oldCourse_joining_code the course_joining_code property value to be removed.
     */
    void removeCourse_joining_code(String oldCourse_joining_code);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#course_name
     */
     
    /**
     * Gets all property values for the course_name property.<p>
     * 
     * @returns a collection of values for the course_name property.
     */
    Collection<? extends String> getCourse_name();

    /**
     * Checks if the class has a course_name property value.<p>
     * 
     * @return true if there is a course_name property value.
     */
    boolean hasCourse_name();

    /**
     * Adds a course_name property value.<p>
     * 
     * @param newCourse_name the course_name property value to be added
     */
    void addCourse_name(String newCourse_name);

    /**
     * Removes a course_name property value.<p>
     * 
     * @param oldCourse_name the course_name property value to be removed.
     */
    void removeCourse_name(String oldCourse_name);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
