package swe;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Department <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public interface Department extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_address
     */
     
    /**
     * Gets all property values for the department_address property.<p>
     * 
     * @returns a collection of values for the department_address property.
     */
    Collection<? extends String> getDepartment_address();

    /**
     * Checks if the class has a department_address property value.<p>
     * 
     * @return true if there is a department_address property value.
     */
    boolean hasDepartment_address();

    /**
     * Adds a department_address property value.<p>
     * 
     * @param newDepartment_address the department_address property value to be added
     */
    void addDepartment_address(String newDepartment_address);

    /**
     * Removes a department_address property value.<p>
     * 
     * @param oldDepartment_address the department_address property value to be removed.
     */
    void removeDepartment_address(String oldDepartment_address);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_id
     */
     
    /**
     * Gets all property values for the department_id property.<p>
     * 
     * @returns a collection of values for the department_id property.
     */
    Collection<? extends Integer> getDepartment_id();

    /**
     * Checks if the class has a department_id property value.<p>
     * 
     * @return true if there is a department_id property value.
     */
    boolean hasDepartment_id();

    /**
     * Adds a department_id property value.<p>
     * 
     * @param newDepartment_id the department_id property value to be added
     */
    void addDepartment_id(Integer newDepartment_id);

    /**
     * Removes a department_id property value.<p>
     * 
     * @param oldDepartment_id the department_id property value to be removed.
     */
    void removeDepartment_id(Integer oldDepartment_id);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_name
     */
     
    /**
     * Gets all property values for the department_name property.<p>
     * 
     * @returns a collection of values for the department_name property.
     */
    Collection<? extends String> getDepartment_name();

    /**
     * Checks if the class has a department_name property value.<p>
     * 
     * @return true if there is a department_name property value.
     */
    boolean hasDepartment_name();

    /**
     * Adds a department_name property value.<p>
     * 
     * @param newDepartment_name the department_name property value to be added
     */
    void addDepartment_name(String newDepartment_name);

    /**
     * Removes a department_name property value.<p>
     * 
     * @param oldDepartment_name the department_name property value to be removed.
     */
    void removeDepartment_name(String oldDepartment_name);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
