package swe;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Progress_Report_Submission <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public interface Progress_Report_Submission extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submitted_for
     */
     
    /**
     * Gets all property values for the submitted_for property.<p>
     * 
     * @returns a collection of values for the submitted_for property.
     */
    Collection<? extends Progress_Report> getSubmitted_for();

    /**
     * Checks if the class has a submitted_for property value.<p>
     * 
     * @return true if there is a submitted_for property value.
     */
    boolean hasSubmitted_for();

    /**
     * Adds a submitted_for property value.<p>
     * 
     * @param newSubmitted_for the submitted_for property value to be added
     */
    void addSubmitted_for(Progress_Report newSubmitted_for);

    /**
     * Removes a submitted_for property value.<p>
     * 
     * @param oldSubmitted_for the submitted_for property value to be removed.
     */
    void removeSubmitted_for(Progress_Report oldSubmitted_for);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#file_link
     */
     
    /**
     * Gets all property values for the file_link property.<p>
     * 
     * @returns a collection of values for the file_link property.
     */
    Collection<? extends URI> getFile_link();

    /**
     * Checks if the class has a file_link property value.<p>
     * 
     * @return true if there is a file_link property value.
     */
    boolean hasFile_link();

    /**
     * Adds a file_link property value.<p>
     * 
     * @param newFile_link the file_link property value to be added
     */
    void addFile_link(URI newFile_link);

    /**
     * Removes a file_link property value.<p>
     * 
     * @param oldFile_link the file_link property value to be removed.
     */
    void removeFile_link(URI oldFile_link);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#marks
     */
     
    /**
     * Gets all property values for the marks property.<p>
     * 
     * @returns a collection of values for the marks property.
     */
    Collection<? extends Integer> getMarks();

    /**
     * Checks if the class has a marks property value.<p>
     * 
     * @return true if there is a marks property value.
     */
    boolean hasMarks();

    /**
     * Adds a marks property value.<p>
     * 
     * @param newMarks the marks property value to be added
     */
    void addMarks(Integer newMarks);

    /**
     * Removes a marks property value.<p>
     * 
     * @param oldMarks the marks property value to be removed.
     */
    void removeMarks(Integer oldMarks);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#remarks
     */
     
    /**
     * Gets all property values for the remarks property.<p>
     * 
     * @returns a collection of values for the remarks property.
     */
    Collection<? extends String> getRemarks();

    /**
     * Checks if the class has a remarks property value.<p>
     * 
     * @return true if there is a remarks property value.
     */
    boolean hasRemarks();

    /**
     * Adds a remarks property value.<p>
     * 
     * @param newRemarks the remarks property value to be added
     */
    void addRemarks(String newRemarks);

    /**
     * Removes a remarks property value.<p>
     * 
     * @param oldRemarks the remarks property value to be removed.
     */
    void removeRemarks(String oldRemarks);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submission_timestamp
     */
     
    /**
     * Gets all property values for the submission_timestamp property.<p>
     * 
     * @returns a collection of values for the submission_timestamp property.
     */
    Collection<? extends Object> getSubmission_timestamp();

    /**
     * Checks if the class has a submission_timestamp property value.<p>
     * 
     * @return true if there is a submission_timestamp property value.
     */
    boolean hasSubmission_timestamp();

    /**
     * Adds a submission_timestamp property value.<p>
     * 
     * @param newSubmission_timestamp the submission_timestamp property value to be added
     */
    void addSubmission_timestamp(Object newSubmission_timestamp);

    /**
     * Removes a submission_timestamp property value.<p>
     * 
     * @param oldSubmission_timestamp the submission_timestamp property value to be removed.
     */
    void removeSubmission_timestamp(Object oldSubmission_timestamp);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
