package swe;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Progress_Report <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public interface Progress_Report extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#date
     */
     
    /**
     * Gets all property values for the date property.<p>
     * 
     * @returns a collection of values for the date property.
     */
    Collection<? extends Object> getDate();

    /**
     * Checks if the class has a date property value.<p>
     * 
     * @return true if there is a date property value.
     */
    boolean hasDate();

    /**
     * Adds a date property value.<p>
     * 
     * @param newDate the date property value to be added
     */
    void addDate(Object newDate);

    /**
     * Removes a date property value.<p>
     * 
     * @param oldDate the date property value to be removed.
     */
    void removeDate(Object oldDate);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#description
     */
     
    /**
     * Gets all property values for the description property.<p>
     * 
     * @returns a collection of values for the description property.
     */
    Collection<? extends String> getDescription();

    /**
     * Checks if the class has a description property value.<p>
     * 
     * @return true if there is a description property value.
     */
    boolean hasDescription();

    /**
     * Adds a description property value.<p>
     * 
     * @param newDescription the description property value to be added
     */
    void addDescription(String newDescription);

    /**
     * Removes a description property value.<p>
     * 
     * @param oldDescription the description property value to be removed.
     */
    void removeDescription(String oldDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#maximum_marks
     */
     
    /**
     * Gets all property values for the maximum_marks property.<p>
     * 
     * @returns a collection of values for the maximum_marks property.
     */
    Collection<? extends Integer> getMaximum_marks();

    /**
     * Checks if the class has a maximum_marks property value.<p>
     * 
     * @return true if there is a maximum_marks property value.
     */
    boolean hasMaximum_marks();

    /**
     * Adds a maximum_marks property value.<p>
     * 
     * @param newMaximum_marks the maximum_marks property value to be added
     */
    void addMaximum_marks(Integer newMaximum_marks);

    /**
     * Removes a maximum_marks property value.<p>
     * 
     * @param oldMaximum_marks the maximum_marks property value to be removed.
     */
    void removeMaximum_marks(Integer oldMaximum_marks);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#report_id
     */
     
    /**
     * Gets all property values for the report_id property.<p>
     * 
     * @returns a collection of values for the report_id property.
     */
    Collection<? extends Integer> getReport_id();

    /**
     * Checks if the class has a report_id property value.<p>
     * 
     * @return true if there is a report_id property value.
     */
    boolean hasReport_id();

    /**
     * Adds a report_id property value.<p>
     * 
     * @param newReport_id the report_id property value to be added
     */
    void addReport_id(Integer newReport_id);

    /**
     * Removes a report_id property value.<p>
     * 
     * @param oldReport_id the report_id property value to be removed.
     */
    void removeReport_id(Integer oldReport_id);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
