package swe;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Student <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public interface Student extends Person {

    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#belongs_to
     */
     
    /**
     * Gets all property values for the belongs_to property.<p>
     * 
     * @returns a collection of values for the belongs_to property.
     */
    Collection<? extends Department> getBelongs_to();

    /**
     * Checks if the class has a belongs_to property value.<p>
     * 
     * @return true if there is a belongs_to property value.
     */
    boolean hasBelongs_to();

    /**
     * Adds a belongs_to property value.<p>
     * 
     * @param newBelongs_to the belongs_to property value to be added
     */
    void addBelongs_to(Department newBelongs_to);

    /**
     * Removes a belongs_to property value.<p>
     * 
     * @param oldBelongs_to the belongs_to property value to be removed.
     */
    void removeBelongs_to(Department oldBelongs_to);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#is_part_of
     */
     
    /**
     * Gets all property values for the is_part_of property.<p>
     * 
     * @returns a collection of values for the is_part_of property.
     */
    Collection<? extends Student_Group> getIs_part_of();

    /**
     * Checks if the class has a is_part_of property value.<p>
     * 
     * @return true if there is a is_part_of property value.
     */
    boolean hasIs_part_of();

    /**
     * Adds a is_part_of property value.<p>
     * 
     * @param newIs_part_of the is_part_of property value to be added
     */
    void addIs_part_of(Student_Group newIs_part_of);

    /**
     * Removes a is_part_of property value.<p>
     * 
     * @param oldIs_part_of the is_part_of property value to be removed.
     */
    void removeIs_part_of(Student_Group oldIs_part_of);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#posted_by
     */
     
    /**
     * Gets all property values for the posted_by property.<p>
     * 
     * @returns a collection of values for the posted_by property.
     */
    Collection<? extends Comment> getPosted_by();

    /**
     * Checks if the class has a posted_by property value.<p>
     * 
     * @return true if there is a posted_by property value.
     */
    boolean hasPosted_by();

    /**
     * Adds a posted_by property value.<p>
     * 
     * @param newPosted_by the posted_by property value to be added
     */
    void addPosted_by(Comment newPosted_by);

    /**
     * Removes a posted_by property value.<p>
     * 
     * @param oldPosted_by the posted_by property value to be removed.
     */
    void removePosted_by(Comment oldPosted_by);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_email
     */
     
    /**
     * Gets all property values for the person_email property.<p>
     * 
     * @returns a collection of values for the person_email property.
     */
    Collection<? extends String> getPerson_email();

    /**
     * Checks if the class has a person_email property value.<p>
     * 
     * @return true if there is a person_email property value.
     */
    boolean hasPerson_email();

    /**
     * Adds a person_email property value.<p>
     * 
     * @param newPerson_email the person_email property value to be added
     */
    void addPerson_email(String newPerson_email);

    /**
     * Removes a person_email property value.<p>
     * 
     * @param oldPerson_email the person_email property value to be removed.
     */
    void removePerson_email(String oldPerson_email);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_name
     */
     
    /**
     * Gets all property values for the person_name property.<p>
     * 
     * @returns a collection of values for the person_name property.
     */
    Collection<? extends String> getPerson_name();

    /**
     * Checks if the class has a person_name property value.<p>
     * 
     * @return true if there is a person_name property value.
     */
    boolean hasPerson_name();

    /**
     * Adds a person_name property value.<p>
     * 
     * @param newPerson_name the person_name property value to be added
     */
    void addPerson_name(String newPerson_name);

    /**
     * Removes a person_name property value.<p>
     * 
     * @param oldPerson_name the person_name property value to be removed.
     */
    void removePerson_name(String oldPerson_name);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_password
     */
     
    /**
     * Gets all property values for the person_password property.<p>
     * 
     * @returns a collection of values for the person_password property.
     */
    Collection<? extends String> getPerson_password();

    /**
     * Checks if the class has a person_password property value.<p>
     * 
     * @return true if there is a person_password property value.
     */
    boolean hasPerson_password();

    /**
     * Adds a person_password property value.<p>
     * 
     * @param newPerson_password the person_password property value to be added
     */
    void addPerson_password(String newPerson_password);

    /**
     * Removes a person_password property value.<p>
     * 
     * @param oldPerson_password the person_password property value to be removed.
     */
    void removePerson_password(String oldPerson_password);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#student_batch
     */
     
    /**
     * Gets all property values for the student_batch property.<p>
     * 
     * @returns a collection of values for the student_batch property.
     */
    Collection<? extends String> getStudent_batch();

    /**
     * Checks if the class has a student_batch property value.<p>
     * 
     * @return true if there is a student_batch property value.
     */
    boolean hasStudent_batch();

    /**
     * Adds a student_batch property value.<p>
     * 
     * @param newStudent_batch the student_batch property value to be added
     */
    void addStudent_batch(String newStudent_batch);

    /**
     * Removes a student_batch property value.<p>
     * 
     * @param oldStudent_batch the student_batch property value to be removed.
     */
    void removeStudent_batch(String oldStudent_batch);



    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#student_roll_no
     */
     
    /**
     * Gets all property values for the student_roll_no property.<p>
     * 
     * @returns a collection of values for the student_roll_no property.
     */
    Collection<? extends Integer> getStudent_roll_no();

    /**
     * Checks if the class has a student_roll_no property value.<p>
     * 
     * @return true if there is a student_roll_no property value.
     */
    boolean hasStudent_roll_no();

    /**
     * Adds a student_roll_no property value.<p>
     * 
     * @param newStudent_roll_no the student_roll_no property value to be added
     */
    void addStudent_roll_no(Integer newStudent_roll_no);

    /**
     * Removes a student_roll_no property value.<p>
     * 
     * @param oldStudent_roll_no the student_roll_no property value to be removed.
     */
    void removeStudent_roll_no(Integer oldStudent_roll_no);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
