package swe;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Student_Group <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public interface Student_Group extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#formed_for
     */
     
    /**
     * Gets all property values for the formed_for property.<p>
     * 
     * @returns a collection of values for the formed_for property.
     */
    Collection<? extends Assignment> getFormed_for();

    /**
     * Checks if the class has a formed_for property value.<p>
     * 
     * @return true if there is a formed_for property value.
     */
    boolean hasFormed_for();

    /**
     * Adds a formed_for property value.<p>
     * 
     * @param newFormed_for the formed_for property value to be added
     */
    void addFormed_for(Assignment newFormed_for);

    /**
     * Removes a formed_for property value.<p>
     * 
     * @param oldFormed_for the formed_for property value to be removed.
     */
    void removeFormed_for(Assignment oldFormed_for);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submits
     */
     
    /**
     * Gets all property values for the submits property.<p>
     * 
     * @returns a collection of values for the submits property.
     */
    Collection<? extends Progress_Report_Submission> getSubmits();

    /**
     * Checks if the class has a submits property value.<p>
     * 
     * @return true if there is a submits property value.
     */
    boolean hasSubmits();

    /**
     * Adds a submits property value.<p>
     * 
     * @param newSubmits the submits property value to be added
     */
    void addSubmits(Progress_Report_Submission newSubmits);

    /**
     * Removes a submits property value.<p>
     * 
     * @param oldSubmits the submits property value to be removed.
     */
    void removeSubmits(Progress_Report_Submission oldSubmits);


    /* ***************************************************
     * Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#group_no
     */
     
    /**
     * Gets all property values for the group_no property.<p>
     * 
     * @returns a collection of values for the group_no property.
     */
    Collection<? extends Integer> getGroup_no();

    /**
     * Checks if the class has a group_no property value.<p>
     * 
     * @return true if there is a group_no property value.
     */
    boolean hasGroup_no();

    /**
     * Adds a group_no property value.<p>
     * 
     * @param newGroup_no the group_no property value to be added
     */
    void addGroup_no(Integer newGroup_no);

    /**
     * Removes a group_no property value.<p>
     * 
     * @param oldGroup_no the group_no property value to be removed.
     */
    void removeGroup_no(Integer oldGroup_no);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
