package swe;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Assignment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ASSIGNMENT.<p>
     * 
     */
    public static final OWLClass CLASS_ASSIGNMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Assignment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Class_Post
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLASS_POST.<p>
     * 
     */
    public static final OWLClass CLASS_CLASS_POST = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Class_Post"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Class_Post_Comment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLASS_POST_COMMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CLASS_POST_COMMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Class_Post_Comment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Comment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMENT.<p>
     * 
     */
    public static final OWLClass CLASS_COMMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Comment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Course
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COURSE.<p>
     * 
     */
    public static final OWLClass CLASS_COURSE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Course"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Department
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPARTMENT.<p>
     * 
     */
    public static final OWLClass CLASS_DEPARTMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Department"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Person"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Progress_Report
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROGRESS_REPORT.<p>
     * 
     */
    public static final OWLClass CLASS_PROGRESS_REPORT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Progress_Report"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Progress_Report_Submission
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROGRESS_REPORT_SUBMISSION.<p>
     * 
     */
    public static final OWLClass CLASS_PROGRESS_REPORT_SUBMISSION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Progress_Report_Submission"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Report_Comment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REPORT_COMMENT.<p>
     * 
     */
    public static final OWLClass CLASS_REPORT_COMMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Report_Comment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Student
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STUDENT.<p>
     * 
     */
    public static final OWLClass CLASS_STUDENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Student"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Student_Group
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STUDENT_GROUP.<p>
     * 
     */
    public static final OWLClass CLASS_STUDENT_GROUP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Student_Group"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Teacher
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEACHER.<p>
     * 
     */
    public static final OWLClass CLASS_TEACHER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Teacher"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Teaching_Assistant
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEACHING_ASSISTANT.<p>
     * 
     */
    public static final OWLClass CLASS_TEACHING_ASSISTANT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Teaching_Assistant"));

    /* ***************************************************
     * Class http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Teaching_Staff
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEACHING_STAFF.<p>
     * 
     */
    public static final OWLClass CLASS_TEACHING_STAFF = factory.getOWLClass(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#Teaching_Staff"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assigned_to
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ASSIGNED_TO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ASSIGNED_TO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assigned_to"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assists
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ASSISTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ASSISTS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assists"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#belongs_to
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BELONGS_TO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BELONGS_TO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#belongs_to"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_posted_on
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMMENT_POSTED_ON.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMMENT_POSTED_ON = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_posted_on"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#commented_on
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMMENTED_ON.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMMENTED_ON = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#commented_on"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#formed_for
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FORMED_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FORMED_FOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#formed_for"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#has_assignment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_ASSIGNMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_ASSIGNMENT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#has_assignment"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#has_report
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_REPORT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_REPORT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#has_report"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#is_part_of
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PART_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PART_OF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#is_part_of"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#offered_by
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OFFERED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OFFERED_BY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#offered_by"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#post_of_class
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property POST_OF_CLASS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_POST_OF_CLASS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#post_of_class"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#posted_by
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property POSTED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_POSTED_BY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#posted_by"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submits
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUBMITS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUBMITS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submits"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submitted_for
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUBMITTED_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUBMITTED_FOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submitted_for"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assignment_id
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ASSIGNMENT_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ASSIGNMENT_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assignment_id"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assignment_title
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ASSIGNMENT_TITLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ASSIGNMENT_TITLE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#assignment_title"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#class_post_description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CLASS_POST_DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CLASS_POST_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#class_post_description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#class_post_id
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CLASS_POST_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CLASS_POST_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#class_post_id"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#class_post_timestamp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CLASS_POST_TIMESTAMP.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CLASS_POST_TIMESTAMP = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#class_post_timestamp"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_message
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COMMENT_MESSAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COMMENT_MESSAGE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_message"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_timestamp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COMMENT_TIMESTAMP.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COMMENT_TIMESTAMP = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_timestamp"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_visibility
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COMMENT_VISIBILITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COMMENT_VISIBILITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#comment_visibility"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#course_joining_code
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COURSE_JOINING_CODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COURSE_JOINING_CODE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#course_joining_code"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#course_name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COURSE_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COURSE_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#course_name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#date
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#date"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_address
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEPARTMENT_ADDRESS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEPARTMENT_ADDRESS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_address"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_id
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEPARTMENT_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEPARTMENT_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_id"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEPARTMENT_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEPARTMENT_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#faculty_designation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FACULTY_DESIGNATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FACULTY_DESIGNATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#faculty_designation"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#faculty_id
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FACULTY_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FACULTY_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#faculty_id"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#file_link
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FILE_LINK.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FILE_LINK = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#file_link"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#group_no
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GROUP_NO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GROUP_NO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#group_no"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#marks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MARKS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MARKS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#marks"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#maximum_marks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MAXIMUM_MARKS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MAXIMUM_MARKS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#maximum_marks"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_email
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PERSON_EMAIL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PERSON_EMAIL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_email"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PERSON_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PERSON_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_password
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PERSON_PASSWORD.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PERSON_PASSWORD = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#person_password"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#ps_link
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PS_LINK.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PS_LINK = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#ps_link"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#remarks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property REMARKS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_REMARKS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#remarks"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#report_id
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property REPORT_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_REPORT_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#report_id"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#student_batch
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STUDENT_BATCH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STUDENT_BATCH = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#student_batch"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#student_roll_no
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STUDENT_ROLL_NO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STUDENT_ROLL_NO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#student_roll_no"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submission_timestamp
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SUBMISSION_TIMESTAMP.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SUBMISSION_TIMESTAMP = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submission_timestamp"));


}
