package swe.impl;

import swe.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultStudent_Group <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */
public class DefaultStudent_Group extends WrappedIndividualImpl implements Student_Group {

    public DefaultStudent_Group(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#formed_for
     */
     
    public Collection<? extends Assignment> getFormed_for() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_FORMED_FOR,
                                               DefaultAssignment.class);
    }

    public boolean hasFormed_for() {
	   return !getFormed_for().isEmpty();
    }

    public void addFormed_for(Assignment newFormed_for) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_FORMED_FOR,
                                       newFormed_for);
    }

    public void removeFormed_for(Assignment oldFormed_for) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_FORMED_FOR,
                                          oldFormed_for);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submits
     */
     
    public Collection<? extends Progress_Report_Submission> getSubmits() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUBMITS,
                                               DefaultProgress_Report_Submission.class);
    }

    public boolean hasSubmits() {
	   return !getSubmits().isEmpty();
    }

    public void addSubmits(Progress_Report_Submission newSubmits) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUBMITS,
                                       newSubmits);
    }

    public void removeSubmits(Progress_Report_Submission oldSubmits) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUBMITS,
                                          oldSubmits);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#group_no
     */
     
    public Collection<? extends Integer> getGroup_no() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GROUP_NO, Integer.class);
    }

    public boolean hasGroup_no() {
		return !getGroup_no().isEmpty();
    }

    public void addGroup_no(Integer newGroup_no) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GROUP_NO, newGroup_no);
    }

    public void removeGroup_no(Integer oldGroup_no) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GROUP_NO, oldGroup_no);
    }


}
