package swe.impl;

import swe.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultProgress_Report_Submission <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */
public class DefaultProgress_Report_Submission extends WrappedIndividualImpl implements Progress_Report_Submission {

    public DefaultProgress_Report_Submission(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submitted_for
     */
     
    public Collection<? extends Progress_Report> getSubmitted_for() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SUBMITTED_FOR,
                                               DefaultProgress_Report.class);
    }

    public boolean hasSubmitted_for() {
	   return !getSubmitted_for().isEmpty();
    }

    public void addSubmitted_for(Progress_Report newSubmitted_for) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SUBMITTED_FOR,
                                       newSubmitted_for);
    }

    public void removeSubmitted_for(Progress_Report oldSubmitted_for) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SUBMITTED_FOR,
                                          oldSubmitted_for);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#file_link
     */
     
    public Collection<? extends URI> getFile_link() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FILE_LINK, URI.class);
    }

    public boolean hasFile_link() {
		return !getFile_link().isEmpty();
    }

    public void addFile_link(URI newFile_link) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FILE_LINK, newFile_link);
    }

    public void removeFile_link(URI oldFile_link) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FILE_LINK, oldFile_link);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#marks
     */
     
    public Collection<? extends Integer> getMarks() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MARKS, Integer.class);
    }

    public boolean hasMarks() {
		return !getMarks().isEmpty();
    }

    public void addMarks(Integer newMarks) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MARKS, newMarks);
    }

    public void removeMarks(Integer oldMarks) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MARKS, oldMarks);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#remarks
     */
     
    public Collection<? extends String> getRemarks() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_REMARKS, String.class);
    }

    public boolean hasRemarks() {
		return !getRemarks().isEmpty();
    }

    public void addRemarks(String newRemarks) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_REMARKS, newRemarks);
    }

    public void removeRemarks(String oldRemarks) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_REMARKS, oldRemarks);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#submission_timestamp
     */
     
    public Collection<? extends Object> getSubmission_timestamp() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUBMISSION_TIMESTAMP, Object.class);
    }

    public boolean hasSubmission_timestamp() {
		return !getSubmission_timestamp().isEmpty();
    }

    public void addSubmission_timestamp(Object newSubmission_timestamp) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUBMISSION_TIMESTAMP, newSubmission_timestamp);
    }

    public void removeSubmission_timestamp(Object oldSubmission_timestamp) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SUBMISSION_TIMESTAMP, oldSubmission_timestamp);
    }


}
