package swe.impl;

import swe.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultDepartment <br>
 * @version generated on Tue Mar 29 22:00:16 IST 2022 by shubh
 */
public class DefaultDepartment extends WrappedIndividualImpl implements Department {

    public DefaultDepartment(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_address
     */
     
    public Collection<? extends String> getDepartment_address() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_ADDRESS, String.class);
    }

    public boolean hasDepartment_address() {
		return !getDepartment_address().isEmpty();
    }

    public void addDepartment_address(String newDepartment_address) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_ADDRESS, newDepartment_address);
    }

    public void removeDepartment_address(String oldDepartment_address) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_ADDRESS, oldDepartment_address);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_id
     */
     
    public Collection<? extends Integer> getDepartment_id() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_ID, Integer.class);
    }

    public boolean hasDepartment_id() {
		return !getDepartment_id().isEmpty();
    }

    public void addDepartment_id(Integer newDepartment_id) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_ID, newDepartment_id);
    }

    public void removeDepartment_id(Integer oldDepartment_id) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_ID, oldDepartment_id);
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/shubh/ontologies/2022/2/untitled-ontology-4#department_name
     */
     
    public Collection<? extends String> getDepartment_name() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_NAME, String.class);
    }

    public boolean hasDepartment_name() {
		return !getDepartment_name().isEmpty();
    }

    public void addDepartment_name(String newDepartment_name) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_NAME, newDepartment_name);
    }

    public void removeDepartment_name(String oldDepartment_name) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEPARTMENT_NAME, oldDepartment_name);
    }


}
